import React, { useState } from "react";
import { useApp } from "@/context/AppContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Search, UserPlus, FileText, Activity } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function DoctorDashboard() {
  const { accessRequests, requestAccess, logout, currentUser } = useApp();
  const [searchId, setSearchId] = useState("");
  const { toast } = useToast();
  const [viewingPatient, setViewingPatient] = useState<boolean>(false);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchId === "1234-5678-9012") { // Mock Patient ID
       // Check if already has access
       const existingRequest = accessRequests.find(r => r.patientId === "p1" && r.doctorId === currentUser?.id);
       
       if (existingRequest?.status === "approved") {
         setViewingPatient(true);
       } else if (existingRequest?.status === "pending") {
         toast({ title: "Request Pending", description: "You have already requested access. Waiting for patient approval." });
       } else {
         toast({ title: "Patient Found", description: "Please request access to view records." });
       }
    } else {
      toast({ variant: "destructive", title: "Patient Not Found", description: "Invalid ABHA ID." });
    }
  };

  const handleRequestAccess = () => {
    requestAccess("p1");
    toast({ title: "Request Sent", description: "Access request sent to patient mobile app." });
  };

  if (viewingPatient) {
    return (
      <div className="min-h-screen bg-slate-50">
        <header className="bg-white border-b p-4 flex justify-between items-center">
           <Button variant="ghost" onClick={() => setViewingPatient(false)}>← Back to Search</Button>
           <h1 className="font-bold text-lg">Patient: Rahul Sharma</h1>
        </header>
        <main className="p-6 max-w-5xl mx-auto space-y-6">
           <Card className="border-l-4 border-l-primary">
             <CardHeader>
               <CardTitle>AI Patient Overview</CardTitle>
               <CardDescription>Generated by Gemini 3 based on last 5 years of history</CardDescription>
             </CardHeader>
             <CardContent>
               <p className="text-slate-700 leading-relaxed">
                 The patient, Rahul Sharma (Male, 34), has a history of mild hypertension, stable over the last 4 years. 
                 Recent reports indicate a slight elevation in cholesterol levels (LDL 130 mg/dL), which is a new development compared to previous stable lipid profiles.
                 No significant allergies reported. Medication adherence appears consistent based on refill patterns.
               </p>
             </CardContent>
           </Card>

           <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
             <Card>
               <CardHeader><CardTitle>Recent Vitals</CardTitle></CardHeader>
               <CardContent>
                  <div className="space-y-4">
                    <div className="flex justify-between border-b pb-2">
                      <span className="text-muted-foreground">Blood Pressure</span>
                      <span className="font-medium">120/80</span>
                    </div>
                    <div className="flex justify-between border-b pb-2">
                      <span className="text-muted-foreground">SpO2</span>
                      <span className="font-medium">98%</span>
                    </div>
                    <div className="flex justify-between border-b pb-2">
                      <span className="text-muted-foreground">Weight</span>
                      <span className="font-medium">72.5 kg</span>
                    </div>
                  </div>
               </CardContent>
             </Card>

             <Card>
               <CardHeader><CardTitle>Recent Reports</CardTitle></CardHeader>
               <CardContent>
                 <ul className="space-y-3">
                   <li className="flex justify-between items-center p-2 bg-slate-100 rounded">
                     <span className="text-sm font-medium">Lipid Profile</span>
                     <span className="text-xs text-muted-foreground">Jan 10, 2026</span>
                   </li>
                   <li className="flex justify-between items-center p-2 bg-slate-100 rounded">
                     <span className="text-sm font-medium">Chest X-Ray</span>
                     <span className="text-xs text-muted-foreground">Nov 20, 2025</span>
                   </li>
                 </ul>
               </CardContent>
             </Card>
           </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      <header className="bg-white border-b p-4 flex justify-between items-center">
        <div className="flex items-center space-x-2">
           <div className="h-8 w-8 bg-blue-600 rounded flex items-center justify-center text-white font-bold">Dr</div>
           <span className="font-heading font-bold">MediVault MD</span>
        </div>
        <Button variant="ghost" onClick={logout}>Logout</Button>
      </header>

      <main className="flex-1 p-6 max-w-2xl mx-auto w-full flex flex-col justify-center">
        <div className="text-center mb-10">
          <h1 className="text-3xl font-bold mb-2">Find a Patient</h1>
          <p className="text-muted-foreground">Enter ABHA ID to request access to records</p>
        </div>

        <Card>
          <CardContent className="pt-6">
            <form onSubmit={handleSearch} className="flex gap-2">
              <Input 
                placeholder="Enter ABHA ID (e.g. 1234-5678-9012)" 
                className="text-lg h-12"
                value={searchId}
                onChange={(e) => setSearchId(e.target.value)}
              />
              <Button type="submit" size="lg" className="px-8 bg-blue-600 hover:bg-blue-700">
                <Search className="h-5 w-5" />
              </Button>
            </form>

            {searchId === "1234-5678-9012" && (
              <div className="mt-6 p-4 border rounded-lg bg-blue-50 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 bg-blue-100 rounded-full flex items-center justify-center text-blue-600">
                    <UserPlus className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="font-bold text-slate-900">Rahul Sharma</p>
                    <p className="text-xs text-slate-500">Male, 34 Years</p>
                  </div>
                </div>
                {accessRequests.find(r => r.patientId === "p1" && r.doctorId === currentUser?.id) ? (
                  <Button variant="outline" disabled>Request Sent</Button>
                ) : (
                  <Button onClick={handleRequestAccess}>Request Access</Button>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
